TEST_API_KEY_BINANCE_SPOT = "xxx"
TEST_API_SECRET_BINANCE_SPOT = "xxx"

TEST_API_KEY_BINANCE_FUTURE = "xxx"
TEST_API_SECRET_BINANCE_FUTURE = "xxx"

TEST_API_KEY_SET = "xxx"
TEST_API_SECRET_SET = "xxx"

LINE_NOTIFY_API = "xxx"
